add modal to lec3
js-tasks-ru/htmlcss-20220811_viktor02 pull request #12
Opened 2022-08-24 14:03 UTC by vkoragin

2022-08-24 14:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-24 14:38 UTC, GSemikozov requested changes

2022-08-24 14:38 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal_wrapper {
.modal__wrapper

2022-08-24 14:38 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  display: none;
именно здесь позиционируем как fixed, причем растягиваем на всю ширину и высоту, чтобы задать полупрозрачный фон (используем rgba чтобы прозрачным был только фон)

2022-08-24 14:38 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
а здесь уже либо relative  либо absolute

2022-08-24 14:38 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
если зададим на уровне блока фон через rgba, не нужно будет использовать лишний элемент

2022-08-24 15:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-24 15:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-24 15:47 UTC, vkoragin commented on 05-lection3/02-modal/modal.css
> +.modal_wrapper {
пофиксил

2022-08-24 15:47 UTC, vkoragin commented on 05-lection3/02-modal/modal.css
> +  display: none;
перенес

2022-08-24 15:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-24 15:47 UTC, vkoragin commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
поменял

2022-08-24 15:48 UTC, vkoragin commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
удалил

2022-08-25 11:56 UTC, GSemikozov approved these changes

2022-08-25 11:57 UTC, GSemikozov approved these changes

2022-08-25 11:57 UTC, merged