add bg to lec4
js-tasks-ru/htmlcss-20220811_viktor02 pull request #16
Opened 2022-08-31 19:51 UTC by vkoragin

2022-08-31 19:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-31 21:11 UTC, GSemikozov requested changes

2022-08-31 21:11 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 401px) and (max-width: 768px) {
если выбрали mobile-first, нужно удалить max-width на всех уровнях, это излишне

2022-08-31 21:11 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 400px) {
лишний медиа-запрос, этот размер картинки - по умолчанию

2022-09-01 05:40 UTC, vkoragin commented on 06-lection4/02-background-image/background-image.css
> +@media (min-width: 401px) and (max-width: 768px) {
поправил

2022-09-01 05:40 UTC, vkoragin commented on 06-lection4/02-background-image/background-image.css
> +@media (max-width: 400px) {
поправил

2022-09-01 05:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-01 15:41 UTC, GSemikozov approved these changes

2022-09-01 15:41 UTC, merged