add toggler to lecture5
js-tasks-ru/htmlcss-20220811_viktor02 pull request #19
Opened 2022-09-05 18:39 UTC by vkoragin

2022-09-05 18:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-07 15:48 UTC, GSemikozov requested changes

2022-09-07 15:48 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.checkbox {
на самом деле это toggle ))

2022-09-07 15:48 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  transform: translate(2px, -50%);
маленькая оптимизация - можно двигать только по оси X

2022-09-07 17:12 UTC, vkoragin commented on 07-lection5/03-toggler/toggler.css
> +.checkbox {
поправил

2022-09-07 17:13 UTC, vkoragin commented on 07-lection5/03-toggler/toggler.css
> +  transform: translate(2px, -50%);
поправил

2022-09-08 15:39 UTC, GSemikozov requested changes

2022-09-08 15:39 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  transform: translateX(2px);
тогда координату лучше задать: left: 0

2022-09-08 15:49 UTC, vkoragin commented on 07-lection5/03-toggler/toggler.css
> +  transform: translateX(2px);
задал

2022-09-08 17:25 UTC, GSemikozov approved these changes

2022-09-08 17:25 UTC, merged