add skeleton to lec2
js-tasks-ru/htmlcss-20220811_viktor02 pull request #6
Opened 2022-08-22 12:51 UTC by vkoragin

2022-08-22 12:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-22 15:46 UTC, GSemikozov requested changes

2022-08-22 15:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
не стоит жестко ограничивать

2022-08-22 15:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line:last-child {
не всегда ведь так может потребоваться делать (например, в другой вариации будет 3 лении вместо 2), поэтому лучше использовать более предсказуемый gap на уровне родителя

2022-08-22 15:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title {
.skeleton__title и .skeleton__subTitle лучше оформлять не как отдельные элементы, а как модификаторы .skeleton__line

2022-08-22 18:38 UTC, vkoragin commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
поправил

2022-08-22 18:38 UTC, vkoragin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line:last-child {
поправил

2022-08-22 18:38 UTC, vkoragin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__title {
поправил

2022-08-23 08:00 UTC, GSemikozov approved these changes

2022-08-23 08:00 UTC, merged