add tooltip to lec3
js-tasks-ru/htmlcss-20220811_viktor02 pull request #9
Opened 2022-08-24 09:25 UTC by vkoragin

2022-08-24 09:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-25 11:54 UTC, GSemikozov requested changes

2022-08-25 11:54 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
глобальные стили на уровне блока не добавляем. Если это вспомогательные стили которые нужны только для текущей страницы - можно на хтмл странице в тег style добавить

2022-08-25 14:54 UTC, vkoragin commented on 05-lection3/01-tooltip/tooltip.css
> +body {
перенес в хтмл

2022-08-27 13:27 UTC, GSemikozov approved these changes

2022-08-27 13:27 UTC, merged